{
 "title": "Statistics",
 "description": "Dishy Statistics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "InfluxDB DataSource", "query": "starlinkstats" },
   {
    "name": "TBL_STATS",
    "label": "Table name for Statistics",
    "query": "spacex.starlink.user_terminal.status"
   }
  ]
 },
 "panels": [
  {
   "title": "Starlink System Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"state\" AS \"State\", \"alert_roaming\" AS \"Roaming\", \"currently_obstructed\" AS \"Obstructed\", \"alert_unexpected_location\" AS \"Bad Location\", \"alert_thermal_throttle\" AS \"Temp Throttled\", \"alert_thermal_shutdown\" AS \"Temp Shutdown\", \"alert_motors_stuck\" AS \"Motors Stuck\", \"software_version\" AS \"Software Version\", \"alert_slow_ethernet_speeds\" AS \"Slow Speed\", \"alert_is_heating\" AS \"Heating\", \"alert_mast_not_near_vertical\" AS \"Mast Not Vertical\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "currently_obstructed" ], "type": "field" },
       { "params": [ "Obstructed" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_unexpected_location" ], "type": "field" },
       { "params": [ "Unexpected Location" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_throttle" ], "type": "field" },
       { "params": [ "Temp Throttled" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_shutdown" ], "type": "field" },
       { "params": [ "Temp Shutdown" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_motors_stuck" ], "type": "field" },
       { "params": [ "Motors Stuck" ], "type": "alias" }
      ],
      [
       { "params": [ "software_version" ], "type": "field" },
       { "params": [ "" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_slow_ethernet_speeds" ], "type": "field" },
       { "params": [ "Slow Speed" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_mast_not_near_vertical" ], "type": "field" },
       { "params": [ "Mast Not Vertical" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_is_heating" ], "type": "field" },
       { "params": [ "Heating" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_roaming" ], "type": "field" },
       { "params": [ "Roaming" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Current Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Current Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ],
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Drop Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "pop_ping_drop_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dish Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Best Download Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Best Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency & Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" }
      ],
      [
       { "params": [ "pop_ping_drop_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Firmware",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "software_version" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Obstructions Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "fraction_obstructed" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "Percent Obstructed" ], "type": "alias" }
      ],
      [
       { "params": [ "obstruction_duration" ], "type": "field" }
      ],
      [
       { "params": [ "obstruction_interval" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}